name: Python Style Checker
on:
  push:
    branches:
      - master
      - takho
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
    - uses: andymckay/pycodestyle-action@0.1.3
