name: Python Style Checker
on:
  push:
    branches:
      - master
      - takho
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/pycodestyle-action@0.1.3
